---
title: "Experiences"
---

**Paraeducator, San Mateo-Foster City School District; San Mateo, CA — Sep. 2023 - June 2024**

I assisted the lead teacher with the district's after school program. I supervised, as well as led, activities; helped with homework during homework time;

**Part-Time Stock Associate, Under Armour; San Diego, CA — Aug. 2022 - Dec. 2022**

I processed shipments, completed replenishment, and fulfilled online and in-store pickup orders. I also assisted on sales floor.

**Swim Instructor, Noonan Family Swim School; Del Mar, CA — Aug. 2021 - Nov. 2021**

I taught children 2 years and older. I devised lessons to progress students’ skills (based on learn-to-swim curriculum) and assessed whether students were ready to progress to the next skill level.

**Runner, UC San Diego Health; San Diego, CA — Jan. 2021 - May 2021**

I volunteered at the Petco Park Vaccination Superstation. I coordinated between charge nurse and vaccinators, stocked supply carts for vaccinators, prepared vaccination kits (alcohol wipe, bandaid, vaccination card, sticker), and passed out vaccination cards.

**High School Student Poll Worker, San Mateo County Assessor-County Clerk- Recorder & Elections, San Mateo County, CA — Nov. 2018**

I participated in a program for eligible high school students to work Election Day at a poll. I greeted voters, facilitated paperwork, and passed out stickers.

**Adoptee Volunteer, Chunhui China Care Home, Beijing, China — July 2018**

The summer before my senior year of high school, I went on a trip with two other girls from my adoption group. We volunteered with other Chinese American adoptees at the Chunhui China Care Home in Beijing, China. The children at the home came from around the country and were awaiting or recovering from medical treatment in Beijing. The trip was organized by [OneSky](https://onesky.org "https://onesky.org") and [China's Children International](https://chinaschildreninternational.org "https://chinaschildreninternational.org").
